# remapping pane switching
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# remapping pane resizing
#bind -n C-h resize-pane -L
#bind -n C-l resize-pane -R
bind -n C-k resize-pane -U
bind -n C-j resize-pane -D

set -s escape-time 0

# open new windows on same as prev path
bind c new-window -c "#{pane_current_path}"

# panes
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=blue'

# statusline
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=black bg=yellow'

set -g status-left ''
set -g status-left-length 10

set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

# messages
set -g message-style 'fg=white bg=blue bold'
